# Generated by Django 5.1.2 on 2025-02-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='cadastrodadospessoais',
            name='naturalidade',
        ),
    ]
